
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agzjfbvfckylcqqqpuuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnempmYnZmY2t5bGNxcXFwdXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzI4NTMsImV4cCI6MjA2MjgwODg1M30.r6D5FkV4UIVDNevXuAeqN_DbgGqGQ6iHfq0_bc-IYkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
